<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DaftarRiwayat_Transaksi10</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>DaftarRiwayat_Transaksi10.Program</StartupObject>

	<UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>